table Map-VendorICC
	lineageTag: 8c15b3f5-c0bf-49e6-a131-91603a8a0d9a

	column nvendorlocationid
		dataType: int64
		formatString: 0
		lineageTag: 53d82291-ad08-4c55-9efd-e1ee2bbd0ad1
		summarizeBy: sum
		sourceColumn: nvendorlocationid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cservicetype
		dataType: string
		lineageTag: 6aa38b2d-6ea1-46fe-9f5c-97fb3876ca43
		summarizeBy: none
		sourceColumn: cservicetype

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Map-VendorICC-024bd54b-d4e6-47e2-ac6c-5cb592a42eaf = m
		mode: import
		queryGroup: MAPPING\auto
		source =
				let
				    Source = vendorlocationservicetype,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"nvendorlocationid", "cservicetype"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each [cservicetype] = "icc"),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows")
				in
				    #"Removed Duplicates"

	changedProperty = IsHidden

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":["nvendorlocationid","cservicetype"],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/SQL/10.200.1.74;epHenkelIT/dbo/vendorlocationservicetype.{nvendorlocationid,1}","Server.Database\\/2/SQL/10.200.1.74;epHenkelIT/dbo/vendorlocationservicetype.{cservicetype,2}"],"ColumnCount":2,"KeyColumnNames":["nvendorlocationid","cservicetype"],"ColumnIdentities":["Server.Database\\/2/SQL/10.200.1.74;epHenkelIT/dbo/vendorlocationservicetype.{nvendorlocationid,1}","Server.Database\\/2/SQL/10.200.1.74;epHenkelIT/dbo/vendorlocationservicetype.{cservicetype,2}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

