table 'Special Bills'
	lineageTag: b31a0f64-5de5-4972-8c4a-517e52a8a7e2

	column entity
		dataType: string
		lineageTag: d9dc729b-7d86-48a8-9ea7-a4180933df33
		summarizeBy: none
		sourceColumn: entity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dataCategory
		dataType: string
		lineageTag: b96f6c23-eebb-4fbc-81ef-01d57029d2a6
		summarizeBy: none
		sourceColumn: dataCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.njobsbid'
		dataType: string
		lineageTag: d2e10c0f-bdbe-41b4-a168-9ac0a870c88f
		summarizeBy: none
		sourceColumn: Data.njobsbid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.nrequestid'
		dataType: string
		lineageTag: 8eb2ddbd-c8bc-4a68-ae9c-8abc8f611b32
		summarizeBy: none
		sourceColumn: Data.nrequestid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.csbcode'
		dataType: string
		lineageTag: 5b9f7255-aa7f-46f3-b1c4-41acec83a891
		summarizeBy: none
		sourceColumn: Data.csbcode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.cvalue'
		dataType: string
		lineageTag: 56826c07-75f1-4aba-9722-08e05be79d3f
		summarizeBy: none
		sourceColumn: Data.cvalue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.lsplit'
		dataType: string
		lineageTag: df77da6b-7092-43eb-b651-c196b3f1fa18
		summarizeBy: none
		sourceColumn: Data.lsplit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.lmultiplepredefinevalue'
		dataType: string
		lineageTag: fb4dfc31-4caa-4dd1-9150-9b97201ce12e
		summarizeBy: none
		sourceColumn: Data.lmultiplepredefinevalue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.dmodified'
		dataType: string
		lineageTag: 25015070-8ea4-43b7-bb00-3afd0f0e89be
		summarizeBy: none
		sourceColumn: Data.dmodified

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.nmodifiedbywho'
		dataType: string
		lineageTag: 0c8702c7-6fa7-42b7-9ecb-a25af0f9dc22
		summarizeBy: none
		sourceColumn: Data.nmodifiedbywho

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.nmodifiedby'
		dataType: string
		lineageTag: 6bcb9bfe-e20d-4228-9eb3-7f762c769056
		summarizeBy: none
		sourceColumn: Data.nmodifiedby

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.ncreatedbywho'
		dataType: string
		lineageTag: eb8c2c4d-6226-4f6c-a8a8-a4e54a55ff30
		summarizeBy: none
		sourceColumn: Data.ncreatedbywho

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.ncreatedby'
		dataType: string
		lineageTag: 9dc7c993-631f-487c-8327-ddf8d2792f3d
		summarizeBy: none
		sourceColumn: Data.ncreatedby

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data.dcreated'
		dataType: string
		lineageTag: 04340a5a-a5cd-4344-80ab-82276024abe7
		summarizeBy: none
		sourceColumn: Data.dcreated

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: 4695bee0-911a-4273-93a0-e32bc315f6c6
		summarizeBy: none
		sourceColumn: Tags

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entityName
		dataType: string
		lineageTag: 38b2f135-24e2-4406-a9fa-6f08086132b1
		summarizeBy: none
		sourceColumn: entityName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column version
		dataType: string
		lineageTag: 9f375818-e629-4a86-90b5-40e049ae2a85
		summarizeBy: none
		sourceColumn: version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemKind
		dataType: string
		lineageTag: 7166d67e-0421-4cb4-88c6-97ddeb0b0daf
		summarizeBy: none
		sourceColumn: ItemKind

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ItemName
		dataType: string
		lineageTag: 7fc82845-8ea2-4075-9610-caef7db7758d
		summarizeBy: none
		sourceColumn: ItemName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsLeaf
		dataType: string
		lineageTag: 622a8071-db66-45d5-bc2e-1ead55692ad6
		summarizeBy: none
		sourceColumn: IsLeaf

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cdesc
		dataType: string
		lineageTag: eef4265f-a30e-460b-8f12-fca4dfc642b6
		summarizeBy: none
		sourceColumn: cdesc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Special Bills' = m
		mode: import
		queryGroup: SOURCE
		source =
				let
				  tablename = "jobspecialbill",
				    Source = PowerPlatform.Dataflows(null),
				    ID = Source{[Id="Workspaces"]}[Data],
				    Workspace = ID{[workspaceName=#"Workspace Name"]}[Data],
				    DataFlow = Workspace{[dataflowName= List.Single(DFName)]}[Data],
				    #"Filtered Rows1" = Table.SelectRows(DataFlow, each ([entity] = "jobspecialbill")),
				    #"Expanded Data" = Table.ExpandTableColumn(#"Filtered Rows1", "Data", {"njobsbid", "nrequestid", "csbcode", "cvalue", "lsplit", "lmultiplepredefinevalue", "dmodified", "nmodifiedbywho", "nmodifiedby", "ncreatedbywho", "ncreatedby", "dcreated"}, {"Data.njobsbid", "Data.nrequestid", "Data.csbcode", "Data.cvalue", "Data.lsplit", "Data.lmultiplepredefinevalue", "Data.dmodified", "Data.nmodifiedbywho", "Data.nmodifiedby", "Data.ncreatedbywho", "Data.ncreatedby", "Data.dcreated"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded Data", {"Data.csbcode"}, globalspecialbill_desc, {"csbcode"}, "globalspecialbill_desc", JoinKind.LeftOuter),
				    #"Expanded globalspecialbill_desc" = Table.ExpandTableColumn(#"Merged Queries", "globalspecialbill_desc", {"cdesc"}, {"cdesc"})
				in
				    #"Expanded globalspecialbill_desc"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

