table 'Requisition Measures'
	lineageTag: 31e6f434-1753-48ab-aa83-ec3ea1a90390

	measure 'Requisitions Approved' =
			
			CALCULATE(DISTINCTCOUNT('jobrequest'[Requisition #]),jobrequest[Go Live Filter] <> "Go Live",
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Approved Date]
			    )
			)
		formatString: #,0
		lineageTag: f60f1856-b0f9-496e-ab34-54284af8c049

		changedProperty = IsHidden

	measure 'Requisitions Filled' =
			
			CALCULATE(DISTINCTCOUNT(assignment[nrequestid]),jobrequest[Go Live Filter] <> "Go Live",
			    'assignment'[Hire Date] <> BLANK(),
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Approved Date]
			    )
			)
		formatString: #,0
		lineageTag: 6b13fc72-721d-43d9-b864-fd7ed6bc3ae4

		changedProperty = IsHidden

	measure 'Requisitions Filled %' =
			DIVIDE(
			[Requisitions Filled],[Requisitions Approved])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e474bdbd-8db4-48c9-a230-97998fa75bff

		changedProperty = IsHidden

	measure 'Requisitions Submitted To' =
			
			CALCULATE(DISTINCTCOUNT(assignment[nrequestid]),jobrequest[Go Live Filter] <> "Go Live",
			    'assignment'[Assignment #] > 0,
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Approved Date]
			    )
			)
		formatString: #,0
		lineageTag: 08af6ed9-4931-4a99-9afb-12e39177176f

		changedProperty = IsHidden

	measure 'Requisitions Submitted %' =
			DIVIDE(
			[Requisitions Submitted To],[Requisitions Approved])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c6039012-d2b8-494a-9fa5-4736d4fae066

		changedProperty = IsHidden

	measure 'Requisitions Cancelled' =
			
			CALCULATE([Requisitions Approved],
			    jobrequest[Requisition Status] = "Cancelled"
			)
		formatString: #,0
		lineageTag: 0be76f01-7310-4a20-a146-e46632610567

		changedProperty = IsHidden

	measure 'Requisitions Created' =
			
			CALCULATE(DISTINCTCOUNT('jobrequest'[Requisition #]),jobrequest[Go Live Filter] <> "Go Live",
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Create Date]
			    )
			)
		formatString: 0
		lineageTag: ab2dbc85-07b9-455d-b6b7-8d6b380d47e6

		changedProperty = IsHidden

	measure 'Positions Approved' =
			
			CALCULATE(SUM('jobrequest'[Positions]),jobrequest[Go Live Filter] <> "Go Live",
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Approved Date]
			    )
			)
		formatString: #,0
		lineageTag: ffcf7479-f0d0-4fc6-a8b4-1a734b5ad425

		changedProperty = IsHidden

	measure 'Positions Filled' =
			
			CALCULATE(DISTINCTCOUNT(assignment[Assignment #]),jobrequest[Go Live Filter] <> "Go Live",
			    'assignment'[Hire Date] <> BLANK(),
			    TREATAS(
			        VALUES('Date Table'[Date]),
			        'jobrequest'[Requisition Approved Date]
			    )
			)
		formatString: #,0
		lineageTag: 085d8378-b65b-4f77-9fbb-3ae8ff6f913d

		changedProperty = IsHidden

	measure 'UI-Reqs_01 YOY %' =
			
			if(or([UI-Reqs_01] = blank(), [UI-Reqs_01 SPLY] = BLANK()), BLANK(),
			([UI-Reqs_01] - [UI-Reqs_01 SPLY]) / [UI-Reqs_01 SPLY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d2bbe84a-a6c4-4af8-a261-da5b2861dc42

		changedProperty = IsHidden

	measure 'UI-Reqs_01 SPLY' =
			
			CALCULATE([UI-Reqs_01],
			ALL('Date Table'),
			SAMEPERIODLASTYEAR('Date Table'[Date]))
		formatString: 0
		lineageTag: 93b5255d-86fe-49c9-8793-c2aa7de29100

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure UI-Reqs_01 =
			
			switch(SELECTEDVALUE('UI-Slicer Selection'[User Selection]),
			    "Reqs Approved",[Requisitions Approved],
			    "Reqs Approved & Submitted To",[Requisitions Submitted To],
			    "Reqs Filled",[Requisitions Filled],
			    "Reqs Cancelled",[Requisitions Cancelled],
			    "Positions Approved",[Positions Approved],
			    "Positions Filled",[Positions Filled],
			    "Null")
		formatString: 0
		lineageTag: b51af4e0-7010-4725-9524-5415d62ba2ef

		changedProperty = IsHidden

	measure 'Open Positions' = CALCULATE([Positions Approved],jobrequest[Requisition Status] = "approved")
		formatString: 0
		lineageTag: 1778b498-4f79-45dc-abfc-5c8754c519f2

	measure 'Open Requisitions' = CALCULATE([Requisitions Approved],jobrequest[Requisition Status] = "approved")
		formatString: 0
		lineageTag: abc1f245-6ee4-4899-952a-644590acdbdd

	partition 'Requisition Measures-d33d4570-f9de-4826-92c0-88eabf346c96' = m
		mode: import
		queryGroup: MEASURES
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

